"""
Given a string of words, you need to find the highest scoring word.

Each letter of a word scores points according to its position in the alphabet: a = 1, b = 2, c = 3 etc.

You need to return the highest scoring word as a string.

If two words score the same, return the word that appears earliest in the original string.

All letters will be lowercase and all inputs will be valid.
"""

def high(x):
    words = x.split()
    word_value = 0
    current = 0
    highest = ''
    for word in words:
        for char in word:
            word_value += (ord(char)-96)
        if word_value > current:
            current = word_value
            highest = word
        word_value = 0
    return highest

high('man i need a taxi up to ubud') # -> 'taxi'
high('what time are we climbing up the volcano') # -> 'volcano'
high('take me to semynak') # -> 'semynak'


# not my solution

def high(x):
    return max(x.split(), key=lambda k: sum(ord(c) - 96 for c in k))